"""CLI entry point for thematic-analysis."""

from __future__ import annotations

import re
import shutil
import sys
import textwrap
import urllib.error
import urllib.request
from pathlib import Path

import click
from dotenv import load_dotenv
from openai import OpenAI
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

from .analysis import send_message
from .config import AnalysisConfig, find_config, get_api_key, load_config
from .prompts import parse_prompts
from .resume import (
    determine_resume_point,
    load_conversation,
    save_conversation,
    save_stage_output,
)
from .steps import STAGE_FILES, build_steps

load_dotenv()

console = Console()


# ---------------------------------------------------------------------------
# Config template for init command
# ---------------------------------------------------------------------------

CONFIG_TEMPLATE = textwrap.dedent("""\
    # Thematic Analysis Configuration
    # Generated by: thematic-analysis init

    [settings]
    model = "{model}"
    reasoning_effort = "{reasoning_effort}"
    moderator_name = "{moderator_name}"
    # prompts_file = "./custom-prompts.md"  # uncomment to use custom prompts

    [context]
    research_questions = \"\"\"
    {research_questions}
    \"\"\"

    business_context = \"\"\"
    {business_context}
    \"\"\"
""")


# ---------------------------------------------------------------------------
# Review prompt
# ---------------------------------------------------------------------------


def review_prompt() -> str:
    """Ask the user what to do after viewing a response.

    Returns one of: 'continue', 'retry', 'quit'.
    """
    console.print()
    console.print(
        "[dim]Press [bold]Enter[/bold] to continue, "
        "[bold]r[/bold] to retry, "
        "[bold]q[/bold] to quit[/dim]"
    )
    choice = input("> ").strip().lower()
    if choice == "r":
        return "retry"
    elif choice == "q":
        return "quit"
    return "continue"


# ---------------------------------------------------------------------------
# Click CLI
# ---------------------------------------------------------------------------


@click.group()
def main():
    """AI-powered thematic analysis for customer interview transcripts."""


# ---------------------------------------------------------------------------
# run
# ---------------------------------------------------------------------------


@main.command()
@click.option(
    "--config",
    "config_path",
    type=click.Path(exists=True, path_type=Path),
    default=None,
    help="Path to TOML config file (auto-detected if omitted).",
)
@click.option(
    "--output-dir",
    type=click.Path(path_type=Path),
    default=None,
    help="Output directory (default: output/ next to config).",
)
@click.option(
    "--resume/--no-resume",
    default=True,
    help="Resume from last completed stage (default: resume).",
)
@click.option(
    "--model",
    default=None,
    help="Override model from config.",
)
@click.option(
    "--reasoning-effort",
    default=None,
    type=click.Choice(
        ["none", "minimal", "low", "medium", "high", "xhigh"],
        case_sensitive=False,
    ),
    help="Override reasoning effort from config.",
)
@click.option(
    "--dry-run",
    is_flag=True,
    default=False,
    help="Show what would happen without making API calls.",
)
def run(
    config_path: Path | None,
    output_dir: Path | None,
    resume: bool,
    model: str | None,
    reasoning_effort: str | None,
    dry_run: bool,
) -> None:
    """Run thematic analysis on interview transcripts."""
    # Find config
    if config_path is None:
        config_path = find_config()
        if config_path is None:
            console.print(
                "[red]Error:[/red] No config.toml found in current directory.\n"
                "Either pass [bold]--config path/to/config.toml[/bold] or run "
                "[bold]thematic-analysis init[/bold] to create a project."
            )
            sys.exit(1)
        console.print(f"[dim]Using config: {config_path}[/dim]")

    # Only require API key for actual runs
    api_key = "" if dry_run else get_api_key()

    config_path = config_path.resolve()
    config = load_config(config_path)

    # CLI overrides
    if model:
        config.model = model
    if reasoning_effort:
        config.reasoning_effort = reasoning_effort

    # Validate prompts file
    if not config.prompts_file.exists():
        console.print(
            f"[red]Error:[/red] Prompts file not found: {config.prompts_file}\n"
            f"Remove the prompts_file setting from your config to use the "
            f"built-in default prompts."
        )
        sys.exit(1)

    # Parse prompts and build steps
    stages = parse_prompts(config.prompts_file)
    steps = build_steps(stages, config)

    if not steps:
        console.print("[red]Error:[/red] No stages parsed from prompts file.")
        sys.exit(1)

    # Set up output directory
    if output_dir is None:
        output_dir = config_path.parent / "output"
    output_dir = output_dir.resolve()

    # Print config summary
    console.print(
        Panel(
            f"[bold]Model:[/bold] {config.model}\n"
            f"[bold]Reasoning:[/bold] {config.reasoning_effort or 'default'}\n"
            f"[bold]Moderator:[/bold] {config.moderator_name}\n"
            f"[bold]Transcripts:[/bold] {len(config.transcripts)}\n"
            f"[bold]Stages:[/bold] {len(steps)} steps\n"
            f"[bold]Output:[/bold] {output_dir}",
            title="Thematic Analysis",
            border_style="cyan",
        )
    )

    if dry_run:
        console.print("\n[bold cyan]Dry run[/bold cyan] — no API calls will be made.")
        console.print("\n[bold]Steps:[/bold]")
        for i, step in enumerate(steps):
            console.print(
                f"  {i + 1}. {step.file_prefix}: {step.title} "
                f"→ {step.filename}"
            )
        console.print("\n[bold]Transcripts:[/bold]")
        for t in config.transcripts:
            exists = "ok" if t["path"].exists() else "[red]NOT FOUND[/red]"
            console.print(f"  {t['participant']}: {t['path']} ({exists})")
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    # Resume logic
    start_index = 0
    messages: list[dict] = []

    if resume:
        resume_point = determine_resume_point(output_dir)
        if resume_point > 0:
            existing_messages = load_conversation(output_dir)
            if existing_messages:
                console.print(
                    f"\n[cyan]Found progress:[/cyan] {resume_point} of "
                    f"{len(steps)} steps complete."
                )
                console.print(
                    "[dim]Press Enter to resume, or 'n' to start fresh[/dim]"
                )
                choice = input("> ").strip().lower()
                if choice != "n":
                    start_index = resume_point
                    messages = existing_messages
                    console.print(
                        f"[green]Resuming from step {start_index + 1}[/green]"
                    )
                else:
                    console.print("[yellow]Starting fresh.[/yellow]")

    if start_index >= len(steps):
        console.print(
            "[green]All steps already complete![/green] "
            f"Final report: {output_dir / steps[-1].filename}"
        )
        return

    # Initialize OpenAI client
    client = OpenAI(api_key=api_key, max_retries=3)

    # Run each step
    for idx in range(start_index, len(steps)):
        step = steps[idx]
        step_label = f"Step {idx + 1}/{len(steps)}"
        stage_label = f"Stage {step.file_prefix}: {step.title}"

        console.print()
        console.rule(f"[bold cyan]{step_label} — {stage_label}[/bold cyan]")
        console.print()

        while True:
            user_msg = {"role": "user", "content": step.prompt}
            current_messages = messages + [user_msg]

            try:
                response_text = send_message(
                    client, current_messages, config.model, config.reasoning_effort
                )
            except KeyboardInterrupt:
                console.print("\n[yellow]Interrupted.[/yellow]")
                save_conversation(output_dir, messages)
                console.print(f"[dim]Progress saved to {output_dir}[/dim]")
                sys.exit(0)

            action = review_prompt()

            if action == "retry":
                console.print("[yellow]Retrying...[/yellow]\n")
                continue
            elif action == "quit":
                save_conversation(output_dir, messages)
                console.print(
                    "[dim]Progress saved. Resume with the same command.[/dim]"
                )
                sys.exit(0)

            messages.append(user_msg)
            messages.append({"role": "assistant", "content": response_text})

            filepath = save_stage_output(output_dir, step, response_text)
            save_conversation(output_dir, messages)
            console.print(f"[green]Saved:[/green] {filepath}")
            break

    console.print()
    console.print(
        Panel(
            "[bold green]Analysis complete![/bold green]\n\n"
            f"Final report: {output_dir / steps[-1].filename}\n"
            f"All outputs: {output_dir}",
            border_style="green",
        )
    )


# ---------------------------------------------------------------------------
# init
# ---------------------------------------------------------------------------


def _multiline_input(prompt_text: str, example: str) -> str:
    """Prompt for multiline input with an example shown."""
    console.print(
        Panel(
            f"[dim]Example:[/dim]\n{example}",
            border_style="dim",
        )
    )
    console.print(f"[bold]{prompt_text}[/bold]")
    console.print("[dim]Type or paste your text. Enter a blank line when done.[/dim]")
    lines = []
    while True:
        try:
            line = input()
        except EOFError:
            break
        if line == "" and lines:
            break
        lines.append(line)
    return "\n".join(lines)


@main.command()
@click.argument("name", default="")
def init(name: str) -> None:
    """Create a new analysis project interactively."""
    console.print(
        Panel(
            "[bold]Thematic Analysis — New Project Setup[/bold]\n\n"
            "This will walk you through creating a new analysis project.\n"
            "You can always edit the config.toml file later.",
            border_style="cyan",
        )
    )

    # Project name
    if not name:
        name = Prompt.ask(
            "Project name",
            default="interview-analysis",
        )

    project_dir = Path.cwd() / "projects" / name
    if project_dir.exists():
        if not Confirm.ask(
            f"Directory [bold]{project_dir}[/bold] already exists. Overwrite config?"
        ):
            console.print("[yellow]Cancelled.[/yellow]")
            return

    # Moderator name
    moderator_name = Prompt.ask(
        "Your name (as the interviewer/moderator)",
        default="",
    )
    if not moderator_name:
        console.print(
            "[yellow]Warning:[/yellow] No moderator name set. "
            "The AI may confuse moderator and participant quotes."
        )

    # Research questions
    research_questions = _multiline_input(
        "Enter your research questions (one per line):",
        "1. What gaps exist in the AI security market?\n"
        "2. How are product teams currently approaching AI security?\n"
        "3. What friction points exist between security and product velocity?",
    )

    # Business context
    business_context = _multiline_input(
        "Describe the business context for this research:",
        "We are exploring the AI security market to identify gaps\n"
        "that can be filled with new products. The focus is on\n"
        "understanding how product teams handle security concerns.",
    )

    # Model
    model = Prompt.ask(
        "OpenAI model",
        default="gpt-5.4",
        choices=["gpt-4o", "gpt-5", "gpt-5.4", "gpt-5.5"],
    )

    # Reasoning effort
    reasoning_effort = Prompt.ask(
        "Reasoning effort",
        default="high",
        choices=["none", "minimal", "low", "medium", "high", "xhigh"],
    )

    # Transcript (optional)
    transcript_path = Prompt.ask(
        "Path to transcript file (or press Enter to skip)",
        default="",
    )
    participant = ""
    if transcript_path:
        participant = Prompt.ask("Participant name")

    # Create project directory
    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "transcripts").mkdir(exist_ok=True)
    (project_dir / "output").mkdir(exist_ok=True)

    # Generate config
    config_content = CONFIG_TEMPLATE.format(
        model=model,
        reasoning_effort=reasoning_effort,
        moderator_name=moderator_name,
        research_questions=research_questions,
        business_context=business_context,
    )

    # Add transcript entry if provided
    if transcript_path:
        src = Path(transcript_path).expanduser().resolve()
        if src.exists():
            dest = project_dir / "transcripts" / src.name
            shutil.copy2(src, dest)
            rel_path = f"./transcripts/{src.name}"
            console.print(f"[green]Copied transcript to:[/green] {dest}")
        else:
            rel_path = transcript_path
            console.print(
                f"[yellow]Warning:[/yellow] File not found: {src}. "
                f"Path saved as-is in config."
            )
        config_content += f'\n[[transcripts]]\npath = "{rel_path}"\n'
        config_content += f'participant = "{participant}"\n'

    config_file = project_dir / "config.toml"
    config_file.write_text(config_content, encoding="utf-8")

    # Print summary
    console.print()
    console.print(
        Panel(
            f"[bold green]Project created![/bold green]\n\n"
            f"  Directory: {project_dir}\n"
            f"  Config:    {config_file}\n\n"
            f"[bold]Next steps:[/bold]\n"
            f"  1. Review/edit the config:  [cyan]{config_file}[/cyan]\n"
            f"  2. Add transcripts:         "
            f"[cyan]thematic-analysis import-transcript <file> "
            f"--participant \"Name\"[/cyan]\n"
            f"  3. Run the analysis:        "
            f"[cyan]cd {project_dir} && thematic-analysis run[/cyan]",
            border_style="green",
        )
    )


# ---------------------------------------------------------------------------
# import-transcript
# ---------------------------------------------------------------------------


def _download_google_doc(url: str) -> str:
    """Download a Google Doc as plain text via the public export URL.

    Works for documents shared with 'anyone with the link can view'.
    """
    # Extract document ID from various Google Docs URL formats
    match = re.search(r"/document/d/([a-zA-Z0-9_-]+)", url)
    if not match:
        console.print(
            "[red]Error:[/red] Could not extract document ID from URL.\n"
            "Expected a URL like: "
            "https://docs.google.com/document/d/YOUR_DOC_ID/edit"
        )
        sys.exit(1)

    doc_id = match.group(1)
    export_url = (
        f"https://docs.google.com/document/d/{doc_id}/export?format=txt"
    )

    try:
        req = urllib.request.Request(export_url)
        with urllib.request.urlopen(req, timeout=30) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.HTTPError as e:
        if e.code == 404:
            console.print(
                "[red]Error:[/red] Document not found. Make sure the Google "
                "Doc is shared with 'Anyone with the link'."
            )
        else:
            console.print(f"[red]Error:[/red] HTTP {e.code} downloading document.")
        sys.exit(1)
    except urllib.error.URLError as e:
        console.print(f"[red]Error:[/red] Network error: {e.reason}")
        sys.exit(1)


@main.command("import-transcript")
@click.argument("source")
@click.option(
    "--participant",
    required=True,
    help="Name of the interview participant.",
)
@click.option(
    "--config",
    "config_path",
    type=click.Path(path_type=Path),
    default=None,
    help="Path to config.toml (auto-detected if omitted).",
)
def import_transcript(source: str, participant: str, config_path: Path | None) -> None:
    """Import a transcript from a file or Google Docs URL.

    SOURCE can be a local file path or a Google Docs URL.
    The transcript is copied into the project's transcripts/ directory
    and added to config.toml.
    """
    # Find config
    if config_path is None:
        config_path = find_config()
        if config_path is None:
            console.print(
                "[red]Error:[/red] No config.toml found. Pass --config or "
                "run from a project directory."
            )
            sys.exit(1)

    config_dir = config_path.parent
    transcripts_dir = config_dir / "transcripts"
    transcripts_dir.mkdir(exist_ok=True)

    # Determine if source is a Google Docs URL or a file
    if source.startswith("https://docs.google.com/"):
        console.print(f"[dim]Downloading from Google Docs...[/dim]")
        content = _download_google_doc(source)
        # Generate filename from participant name
        safe_name = re.sub(r"[^\w\s-]", "", participant.lower())
        safe_name = re.sub(r"[\s]+", "-", safe_name)
        filename = f"{safe_name}-transcript.txt"
        dest = transcripts_dir / filename
        dest.write_text(content, encoding="utf-8")
        console.print(f"[green]Downloaded:[/green] {dest}")
    else:
        src = Path(source).expanduser().resolve()
        if not src.exists():
            console.print(f"[red]Error:[/red] File not found: {src}")
            sys.exit(1)
        dest = transcripts_dir / src.name
        shutil.copy2(src, dest)
        console.print(f"[green]Copied:[/green] {dest}")

    # Append to config.toml
    rel_path = f"./transcripts/{dest.name}"
    entry = f'\n[[transcripts]]\npath = "{rel_path}"\nparticipant = "{participant}"\n'
    with open(config_path, "a", encoding="utf-8") as f:
        f.write(entry)

    console.print(
        f"[green]Added to config:[/green] {participant} → {rel_path}"
    )
